### ISSUE TITLE
Django 2.1 view permission support (readonly)

### ISSUE THREAD

**Issue by manelclos** [makinacorpus/django-leaflet#246] opened 2019-01-09 12:35 UTC
Hi, I've long wished django-leaflet supported a readonly view when the geometry field is included in readonly_fields.

Django 2.1 introduces the "view" permission: you can just list and view models in the admin, no edit permission needed. This makes more obvious that read only support is needed.

Is there any effort in that direction?

Thanks,

**Comment by Gagaro** [comment] 2019-03-04 13:53
Hi, there's currently no enhancement done by us. If you want to implement this yourself, feel free to open a PR so I can review/merge it.

**Comment by nemesisdesign** [comment] 2021-12-01 12:58
Is this a duplicate of https://github.com/makinacorpus/django-leaflet/issues/85 or are these 2 different cases?

**Comment by manelclos** [comment] 2021-12-01 15:09
@nemesisdesign it is a duplicate.

**Comment by Gagaro** [comment] 2021-12-07 09:33
Indeed, nice catch. I'll close this one.

**Closed by Gagaro** 2021-12-07 09:33 UTC
Labels: enhancement
