### ISSUE TITLE
Markers not working with ManifestStaticFilesStorage

### ISSUE THREAD

**Issue by Vulum** [makinacorpus/django-leaflet#357] opened 2022-12-16 12:58 UTC
For some reason all teardrop markers are having weird path as indicated in the subject. As a result, the teardrop markers are not visible in django admin maps.
I am using  django-leaflet==0.28.3, Python 3.10.8 and Django==4.1.4
How can I remove this extension `")marker-icon.png`?

**Comment by Gagaro** [comment] 2022-12-20 13:36
How are you displaying the map?

I guess you are using the `ManifestStaticFilesStorage`, do you have an issue with the `StaticFilesStorage`?

**Comment by Vulum** [comment] 2022-12-20 14:17
Hi @Gagaro,

Thank you so much, it worked like magic when I changed from `ManifestStaticFilesStorage` to `StaticFilesStorage`  . 
I was using `ManifestStaticFilesStorage` coz I am running both django and Wagtail CMS in my project to which Wagtail CMS recommended `ManifestStaticFilesStorage`   to prevent outdated JavaScript / CSS assets being served from cache (e.g. after a Wagtail upgrade).
Anyways, thank you once again. For almost 2 weeks I've been searching for a solution until now.

**Comment by Gagaro** [comment] 2022-12-21 10:24
The issue is inside leaflet itself:

```javascript
path = path.replace(/^url\(["']?/, '').replace(/marker-icon\.png["']?\)$/, '');
```

I'm not sure how (or if) we can handle it with `ManifestStaticFilesStorage`.

**Comment by claudep** [comment] 2022-12-21 11:32
This is a duplicate of #342.

**Comment by Gagaro** [comment] 2022-12-21 13:06
Nice catch, thanks :+1: .

**Closed by Gagaro** 2022-12-21 13:06 UTC
Labels: bug
